### ISSUE TITLE
Compile - towards J2543 support - Windows XP

### ISSUE THREAD

**Issue by paladinshiva** [Comer352L/FreeSSM#30] opened 2019-05-19 05:49 UTC
When compiling using latest QT I will not get errors, however it will fail to run on XP.
I have used all QT versions between 5.5.0 and 5.6.3, changing different parameters(deployment, etc.)
However it keeps giving me two consistent errors:
1. It will not make release on earlier versions (<=5.6.3), without giving an error of not being able to copy ++-6.dll(I did try PATH and other fixes), easiest way around it was to deploy the instaslled folder
2. It will start on XP but will terminate with errors if you press any diagnostic button.

**Comment by Matthew-Cherry87** [comment] 2019-05-19 05:54
Copy the missing dll from the QT directory.

Also are you using QT GUI or CLI to compile?

**Comment by Comer352L** [comment] 2019-05-19 16:01
Looks like the dlls that need to be shipped have changed ?
Take a look at line 198+ in FreeSSM.pro ("dllstarget.files = ...").
If libstdc++-6.dll doesn't exist anymore, then I assume newer Qt5 versions ship a newer MinGW/g++ version ?

I can't test the Windows build right now (I'm not using this OS anymore since a long time).
I can test Win 7 in a few days, but XP is definitely unsupported (at least by me).

**Comment by Comer352L** [comment] 2019-05-19 16:05
Hmm... has Qt5 ever been working on Win XP ? Really ? ;)

**Comment by Matthew-Cherry87** [comment] 2019-05-19 22:09
I did encounter this issue under Windows 10 and Qt5. From memory it was only using the GUI. The programme compiled perfectly fine from CLI.

**Comment by paladinshiva** [comment] 2019-05-19 23:23
> Copy the missing dll from the QT directory.
> 
> Also are you using QT GUI or CLI to compile?

mingw32.
Copying or deploying does make it run, but does not solve functionality on WXP

**Comment by paladinshiva** [comment] 2019-05-19 23:27
> Looks like the dlls that need to be shipped have changed ?
> Take a look at line 198+ in FreeSSM.pro ("dllstarget.files = ...").
> If libstdc++-6.dll doesn't exist anymore, then I assume newer Qt5 versions ship a newer MinGW/g++ version ?
> 
It exists. Just will not copy on QT5.5.1 to QT5.6.3 using mingw32
> I can't test the Windows build right now (I'm not using this OS anymore since a long time).
> I can test Win 7 in a few days, but XP is definitely unsupported (at least by me).
That is too bad. Most car diagnostic software works better on WXP and the 1.2.5 FSSM works perfectly.
Except it does not connect to TCU. But since RR does not either it might be just my TCU.
I am going to dedicate as much time as possible to 
A: Successfully run it on WXP
B: Run it with J2534
If you could help even that you will not support WXP, I would still appreciate that.

**Comment by paladinshiva** [comment] 2019-05-19 23:29
> Hmm... has Qt5 ever been working on Win XP ? Really ? ;)

Yes. According to official website: 5.5 can compile and deploy. 5.6 can deploy.
I do apologize for my lack of knowledge for this particular programming environment...
Not something I am fluent with.
If it was Java, or better yet JS, would've been much easier time...

**Comment by paladinshiva** [comment] 2019-05-19 23:31
> I did encounter this issue under Windows 10 and Qt5. From memory it was only using the GUI. The programme compiled perfectly fine from CLI.

Huh, could you outline the steps to compile and install this through CLI?
I was able to compile without errors on any version, and install on W10 with latest QT with no errors, using mingw32

**Comment by Comer352L** [comment] 2019-05-20 17:03
1.) WinXP support is umaintained, sorry.

2.) Only compilation from command line is tested/maintained, and that's what README.TXT describes.
Compilation with Qt Creator etc. should work, too - but no guarantees !

3.) I have tested compilation and installation using Qt 5.12.3 on Win 7 64bit a few minutes ago.
Everything works as expected - with 1 exception:
there is now also a 64bit version of MinGW, which uses a slightly different dll file name for libgcc.
I have commited a fix for that.

4.) Concerning the libstdc++-6.dll copy error: I can confirm it occures with Qt5.2.1 (old !), too.
I wasn't able to track this down, but I assume it was a bug in qmake which has been fixed sometime around Qt5.7.
Looks like the "++-" sequence in the file name was confusing the project file parser...

**Comment by Comer352L** [comment] 2019-05-20 17:54
I have updated README.TXT, trying to incorporate the questions/issues discussed in this thread.
The crap with the Qt framework on Windows is that the installation process changes permanently...

**Comment by Comer352L** [comment] 2019-05-20 18:01
> > Looks like the dlls that need to be shipped have changed ?
> > Take a look at line 198+ in FreeSSM.pro ("dllstarget.files = ...").
> > If libstdc++-6.dll doesn't exist anymore, then I assume newer Qt5 versions ship a newer MinGW/g++ version ?
> 
> It exists. Just will not copy on QT5.5.1 to QT5.6.3 using mingw32

You are right, there was at least limited support up to Qt 5.6:
https://doc.qt.io/archives/qt-5.6/supported-platforms.html

It has been removed with Qt 5.7:
https://doc.qt.io/archives/qt-5.7/supported-platforms.html

**Comment by paladinshiva** [comment] 2019-05-20 23:52
> 1.) WinXP support is unmaintained, sorry.
> 
That is too bad. Any pointers of what I can do to work on enabling support?
I understand that you are not willing.
> 2.) Only compilation from command line is tested/maintained, and that's what README.TXT describes.
> Compilation with Qt Creator etc. should work, too - but no guarantees !
> 
I have never tried anything but CLI.
> 3.) I have tested compilation and installation using Qt 5.12.3 on Win 7 64bit a few minutes ago.
> Everything works as expected - with 1 exception:
> there is now also a 64bit version of MinGW, which uses a slightly different dll file name for libgcc.
> I have commited a fix for that.
> 
> 4.) Concerning the libstdc++-6.dll copy error: I can confirm it occures with Qt5.2.1 (old !), too.
> I wasn't able to track this down, but I assume it was a bug in qmake which has been fixed sometime around Qt5.7.
> Looks like the "++-" sequence in the file name was confusing the project file parser...
Yes.

**Comment by paladinshiva** [comment] 2019-05-20 23:53
> I have updated README.TXT, trying to incorporate the questions/issues discussed in this thread.
> The crap with the Qt framework on Windows is that the installation process changes permanently...

I can't argue with that... lol
But, unfortunately WXP offers maximum compatibility with various car software, and you can make some things work on newer versions.
Nix is highly under supported by OEM.

**Comment by paladinshiva** [comment] 2019-05-20 23:56
> > > Looks like the dlls that need to be shipped have changed ?
> > > Take a look at line 198+ in FreeSSM.pro ("dllstarget.files = ...").
> > > If libstdc++-6.dll doesn't exist anymore, then I assume newer Qt5 versions ship a newer MinGW/g++ version ?
> > 
> > 
> > It exists. Just will not copy on QT5.5.1 to QT5.6.3 using mingw32
> 
> You are right, there was at least limited support up to Qt 5.6:
> https://doc.qt.io/archives/qt-5.6/supported-platforms.html
> 
> It has been removed with Qt 5.7:
> https://doc.qt.io/archives/qt-5.7/supported-platforms.html

Correct.
It doesn't matter however, except avoiding lib.dll error in later versions. Functionality of the code is the same.

**Comment by paladinshiva** [comment] 2019-05-20 23:59
Also, make command doesn't work in XP OR W10. On multiple installations. So maybe you can add that mingw32-make is more likely to work than make.

**Comment by Comer352L** [comment] 2019-05-21 16:18
> Also, make command doesn't work in XP OR W10. On multiple installations. So maybe you can add that mingw32-make is more likely to work than make.

Initially it was just "make".
Then they changed it to "mingw32-make" one day.
After a while, it became "make" again.
Currently it's "mingw32-make" again...

Sorry, I'm not going to waste any time on trying to keep track of the current state...
Both variants are described in README.TXT, it's really not too difficult to try both.

**Comment by Comer352L** [comment] 2019-05-21 16:23
Concerning Windows XP: I simply can't test it.
If anything in FreeSSM needs to be changed to support it, feel free to send a patch.
But I don't expect that to be necessary, problems most likely arise from incompatibilities between the Qt/MinGW and OS versions.

**Comment by Comer352L** [comment] 2019-05-21 16:31
Ok, let's summarize your problem:
You are forced to build on Win XP.
Qt5 doesn't support Win XP anymore since v5.7, so are forced to build with a Qt version < 5.7.
Unfortunately, these old versions seem to have a bug that causes a libstdc++-6.dll copy error during installation of FreeSSM.

I wasn't able to find a quick workaround for this bug (such as quoting) and I don't think it makes sense to spend more time on it, because the bug has already been fixed in recent Qt/MinGW versions.

So I suggest to simply work around the libstdc++-6.dll copy bug by copying the library manually via Explorer. The displayed error message contains all required information (the paths).

**Comment by paladinshiva** [comment] 2019-05-21 16:36
> > Also, make command doesn't work in XP OR W10. On multiple installations. So maybe you can add that mingw32-make is more likely to work than make.
> 
> Initially it was just "make".
> Then they changed it to "mingw32-make" one day.
> After a while, it became "make" again.
> Currently it's "mingw32-make" again...
> 
> Sorry, I'm not going to waste any time on trying to keep track of the current state...
> Both variants are described in README.TXT, it's really not too difficult to try both.

Seems reasonable. I was not aware that the command changed BETWEEN versions. Sad

**Comment by paladinshiva** [comment] 2019-05-21 16:40
> Ok, let's summarize your problem:
> You are forced to build on Win XP.
> Qt5 doesn't support Win XP anymore since v5.7, so are forced to build with a Qt version < 5.7.
> Unfortunately, these old versions seem to have a bug that causes a libstdc++-6.dll copy error during installation of FreeSSM.
> 
> I wasn't able to find a quick workaround for this bug (such as quoting) and I don't think it makes sense to spend more time on it, because the bug has already been fixed in recent Qt/MinGW versions.
> 
> So I suggest to simply work around the libstdc++-6.dll copy bug by copying the library manually via Explorer. The displayed error message contains all required information (the paths).

I really appreciate you taking time and summarizing solutions to this particular problem. 

However that is not as important as actually using the software on WXP. It simply does not work if you press any action(anything except About, Settings) button and crashes. 
I'll try to compile it through QT 4 and see if I am able to make it run.

**Comment by paladinshiva** [comment] 2019-05-21 16:42
I also will check dependencies on the built app in WXP, but I doubt I am missing any libraries

**Comment by Comer352L** [comment] 2019-05-21 16:48
> I really appreciate you taking time and summarizing solutions to this particular problem.
> 
> However that is not as important as actually using the software on WXP. It simply does not work if you press any action(anything except About, Settings) button and crashes.
> I'll try to compile it through QT 4 and see if I am able to make it run.

So this happens with Qt5 < 5.7, too ?
Hmm... wait !
Are you testing with a J2534 interface ?

**Comment by Comer352L** [comment] 2019-05-21 16:56
Compile as debug, and let's see if the output provides anything usable.

**Comment by paladinshiva** [comment] 2019-05-21 18:11
> > I really appreciate you taking time and summarizing solutions to this particular problem.
> > However that is not as important as actually using the software on WXP. It simply does not work if you press any action(anything except About, Settings) button and crashes.
> > I'll try to compile it through QT 4 and see if I am able to make it run.
> 
> So this happens with Qt5 < 5.7, too ?
> Hmm... wait !
> Are you testing with a J2534 interface ?

It doesn't matter what interface I choose in drop down menu.
It just crashes.
And yes, no matter QT5 version used, the ones that I was able to start on WXP would immediately crash upon clicking those buttons.

**Comment by paladinshiva** [comment] 2019-05-21 18:12
> Compile as debug, and let's see if the output provides anything usable.

Will do.

**Comment by Comer352L** [comment] 2019-05-23 17:20
> It doesn't matter what interface I choose in drop down menu.
> It just crashes.
> And yes, no matter QT5 version used, the ones that I was able to start on WXP would immediately crash upon clicking those buttons.

That's weird. 
Are you testing on the same system you were building ?

**Comment by Comer352L** [comment] 2019-05-23 17:49
The libstdc++-6.dll copy error has been reported as Qt-bug 74388:
https://bugreports.qt.io/browse/QTBUG-74388

The only known workaround seems to be using the old 8.3 MS-DOS filename.

Fix applied.

**Comment by paladinshiva** [comment] 2019-05-23 19:29
> > It doesn't matter what interface I choose in drop down menu.
> > It just crashes.
> > And yes, no matter QT5 version used, the ones that I was able to start on WXP would immediately crash upon clicking those buttons.
> 
> That's weird.
> Are you testing on the same system you were building ?

Yes, and also tried deploying and copying.

**Comment by paladinshiva** [comment] 2019-05-23 19:30
> The libstdc++-6.dll copy error has been reported as Qt-bug 74388:
> https://bugreports.qt.io/browse/QTBUG-74388
> 
> The only known workaround seems to be using the old 8.3 MS-DOS filename.
> 
> Fix applied.

 Wow man. You really make feel bad, I have been busy, and you already got all this done!!!
I am going to compile using QT4.8 Right now, test as release, then debug, then QT5.5.1, debug, and then 5.6 debug.

**Comment by Comer352L** [comment] 2019-05-23 19:58
I just noticed that Qt4 is available again for Windows:
https://download.qt.io/archive/qt/4.8/4.8.7/qt-opensource-windows-x86-mingw482-4.8.7.exe

I've update README.txt accordingly.

If you are on Win XP, Qt4 is likely the better choice.

**Comment by Comer352L** [comment] 2019-05-23 20:00
> Wow man. You really make me feel bad, I have been busy, and you already got all this done!!!
> I am going to compile using QT4.8 Right now, test as release, then debug, then QT5.5.1, debug, and then 5.6 debug.

No need to test them all.
Update your local repo and try with 4.8.7 from scratch.
Everything should be fine now.

**Comment by paladinshiva** [comment] 2019-05-23 20:50
Update:
4.8.7 Compiles fine like others.
4.8.7 Will not copy libstdc++-6.dll at all, as in not attempting or describing any output.
4.8.7 Will not copy libwinpthread-1.dll at all, as in not attempting or describing any output.
How did I found out: Error messages upon starting software.
Fix: Manually copy. 
Possible solution: Use QT 5.5.1 or higher. Have not tried.

**Comment by paladinshiva** [comment] 2019-05-23 20:52
Program still crashes. You were absolutely correct and it crashes because J2534 was selected, apparently in previous tries it was by default.
If I change to J2534 it will start crashing.
Going to try to see what is it trying to do while calling for it, and if no success, will try CH40 KKL

**Comment by paladinshiva** [comment] 2019-05-23 21:02
Update:
!!!!!!!!!!!!!!!!!!
WILL NOT CRASH when compiling debug version and goes through all appropriate steps.
Going to test connection with the 02 WRX.

**Comment by paladinshiva** [comment] 2019-05-23 21:08
It will exit on Engine screen while saying "No answer from ECU".
However showing Port version and some ECU information on the screen.
When testing port first time it will give an error of unsuccessful test because SSM1 is not supported.
When testing second time it will report successful test but give a warning that SSM1 is not supported.

**Comment by paladinshiva** [comment] 2019-05-23 21:11
[FREESSMLOG.TXT](https://github.com/Comer352L/FreeSSM/files/3214174/FREESSMLOG.TXT)

**Comment by paladinshiva** [comment] 2019-05-23 21:53
Looking through previous issues, makes me think this is related to Headers issue and to Buffer Clean issue.
Looks like in the code buffer clean up only happens if compiling Debug.

**Comment by Comer352L** [comment] 2019-05-27 19:01
I can't reproduce any of your compilation/installation problems here.
I assume you were testing without the latest commits ?

Anyway, I can indeed reproduce the crash with the J2534 interface.
And yes, it only happens when building as "release".
Looks, like it is caused by g++ optimization "-O2"...
When building as "debug", "-O2" isn't used.

Will have to investigate this further...

**Comment by paladinshiva** [comment] 2019-05-27 20:06
> I can't reproduce any of your compilation/installation problems here.
> I assume you were testing without the latest commits ?
> 
Nope.
Latest commits.
4.8.7 QT
Windows XP
> Anyway, I can indeed reproduce the crash with the J2534 interface.
> And yes, it only happens when building as "release".
> Looks, like it is caused by g++ optimization "-O2"...
> When building as "debug", "-O2" isn't used.
>
Yes, it is weird one.
That is not that big of a deal though, since I can make it work in debug.
The issue is that J2534 is not working.
> Will have to investigate this further...
I successfully used FT232RL KKL cable on Windows XP, 02 WRX ASGC00C, running latest version, debug and with fixes applied.
I cannot access my TCU(4EAT), but I am assuming that is due to this year particular TCU or because KKL does not support some obscure pin.
Not giving up hope of making J2534 OP working, because the errors seem similar to the errors that been fixed before.

**Comment by Comer352L** [comment] 2019-05-31 10:25
> > I can't reproduce any of your compilation/installation problems here.
> > I assume you were testing without the latest commits ?
> 
> Nope.
> Latest commits.
> 4.8.7 QT
> Windows XP

In the meantime I have tested Windows XP with Qt 4.8.7 (MinGW 4.8.2), too.
I also tested Qt 4.8.7 and Qt 5.12.3 on Windows 7 64bit.
Result: zero compilation/installation problems.

**Comment by Comer352L** [comment] 2019-05-31 10:27
> Anyway, I can indeed reproduce the crash with the J2534 interface.
> And yes, it only happens when building as "release".
> Looks, like it is caused by g++ optimization "-O2"...
> When building as "debug", "-O2" isn't used.

Finally killed the beast (the crash).
Fixed with commit commit 3b78de3e63.


Now please update and test on a clean Qt/MinGW installation.
I'm pretty sure there are no more installation issues and the crash is gone.
If you can confirm that, we can start debugging the OpenPort 2.0 interface.

**Comment by paladinshiva** [comment] 2019-06-01 04:42
> > Anyway, I can indeed reproduce the crash with the J2534 interface.
> > And yes, it only happens when building as "release".
> > Looks, like it is caused by g++ optimization "-O2"...
> > When building as "debug", "-O2" isn't used.
> 
> Finally killed the beast (the crash).
> Fixed with commit commit [3b78de3](https://github.com/Comer352L/FreeSSM/commit/3b78de3e631e56479e8f793b6ae024723fa882ad).
> 
> Now please update and test on a clean Qt/MinGW installation.
> I'm pretty sure there are no more installation issues and the crash is gone.
> If you can confirm that, we can start debugging the OpenPort 2.0 interface.

You're the man!!!
No issues while compiling on WXP 4.8.2GW/4.8.7QT. Or any others.
No crashes.

J2534 however gives the same error while accessing engine as before(NOT crashing, it's perfect in that regard), when I ran it through debug. SSM1 error, etc. Same as described earlier.

**Comment by Comer352L** [comment] 2019-06-01 11:18
> You're the man!!!
> No issues while compiling on WXP 4.8.2GW/4.8.7QT. Or any others.
> No crashes.

Good, so I'm now closing this bug report.

> J2534 however gives the same error while accessing engine as before(NOT crashing, it's perfect in that regard), when I ran it through debug. SSM1 error, etc. Same as described earlier.

That's no surprise, the problem is the J2534-library.
Please create a new/separate issue for your problems with OpenPort 2.0 interface.
Also create a new debugging log with the latest code (the reason for the crash might have caused other "ghosts" to appear).
Note that you can easily save the whole debugging output by starting the software from the command line with "freessm > debug.log" (or whatever filename you prefer).

**Closed by Comer352L** 2019-06-01 11:18 UTC
